# 熵变智元AI销售助手 - Ingress网关配置

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-sales-assistant-ingress
  namespace: ai-sales-assistant
  labels:
    app: ai-sales-assistant
    component: gateway
  annotations:
    # Nginx Ingress Controller配置
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
    
    # SSL配置
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    
    # 安全配置
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    
    # 速率限制
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    
    # WebSocket支持
    nginx.ingress.kubernetes.io/proxy-set-headers: "nginx-ingress/websocket-headers"
    
    # CORS配置
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
spec:
  tls:
  - hosts:
    - yourdomain.com
    - api.yourdomain.com
    - monitor.yourdomain.com
    secretName: ai-sales-assistant-tls
  
  rules:
  # 主域名 - API服务
  - host: yourdomain.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      - path: /health
        pathType: Exact
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  
  # API子域名
  - host: api.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ai-sales-assistant-service
            port:
              number: 8000
  
  # 监控子域名
  - host: monitor.yourdomain.com
    http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana-service
            port:
              number: 3000
      - path: /prometheus
        pathType: Prefix
        backend:
          service:
            name: prometheus-service
            port:
              number: 9090

---
# WebSocket专用配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: websocket-headers
  namespace: nginx-ingress
data:
  Connection: "upgrade"
  Upgrade: "$http_upgrade"
  Host: "$host"
  X-Real-IP: "$remote_addr"
  X-Forwarded-For: "$proxy_add_x_forwarded_for"
  X-Forwarded-Proto: "$scheme"

---
# SSL证书配置
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ai-sales-assistant-tls
  namespace: ai-sales-assistant
spec:
  secretName: ai-sales-assistant-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - yourdomain.com
  - api.yourdomain.com
  - monitor.yourdomain.com

---
# Let's Encrypt证书颁发者
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@yourdomain.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

