# 熵变智元AI销售助手 - 持久化存储配置

# 存储类定义
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
  labels:
    app: ai-sales-assistant
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
# 应用上传文件存储
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-sales-assistant-uploads
  namespace: ai-sales-assistant
  labels:
    app: ai-sales-assistant
    component: storage
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 50Gi

---
# 应用日志存储
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-sales-assistant-logs
  namespace: ai-sales-assistant
  labels:
    app: ai-sales-assistant
    component: storage
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 20Gi

---
# 备份存储
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-sales-assistant-backups
  namespace: ai-sales-assistant
  labels:
    app: ai-sales-assistant
    component: backup
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 100Gi

---
# NFS存储类 (用于共享存储)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
  labels:
    app: ai-sales-assistant
provisioner: kubernetes.io/nfs
parameters:
  server: nfs-server.default.svc.cluster.local
  path: /exports
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Retain

